<?php

require_once(HARMONI."DBHandler/InsertQueryResult.interface.php");

/**
 * The InsertQueryResult interface provides the functionality common to all INSERT query results.
 *
 * The InsertQueryResult interface provides the functionality common to all INSERT query results.
 * For example, you can get the primary key for the last insertion, get number of inserted rows, etc.
 * @version $Id: PostGreInsertQueryResult.class.php,v 1.1 2003/07/16 02:55:58 dobomode Exp $
 * @package harmoni.dbc
 * @access public
 * @copyright 2003 
 */

class PostGreInsertQueryResult extends InsertQueryResultInterface  {


	/**
	 * The resource id for this query.
	 * @attribute private integer __resourceId
	 */
	var $_resourceId;

	/**
	 * Gets the last auto increment value that was generated by the INSERT query.
	 * Gets the last auto increment value that was generated by the INSERT query.
	 * @access private
	 * @var integer $_lastAutoIncrementValue The last auto increment value that was generated by the INSERT query.
	 */
	var $_lastAutoIncrementValue;

	/**
	 * Stores the number of rows processed by the query.
	 * Stores the number of rows processed by the query.
	 * @var integer $_numberOfRows The number of rows processed by the query.
	 * @access private
	 */
	var $_numberOfRows;


	/**
	 * Creates a new PostGreINSERTQueryResult object.
	 * @access public
	 * @param integer $resourceId The resource id for this query.
	 * @return object A new PostGreINSERTQueryResult object.
	 */
	function PostGreInsertQueryResult($resourceId) {
		// ** parameter validation
		$resourceRule =& new ResourceValidatorRule();
		ArgumentValidator::validate($resourceId, $resourceRule, true);
		// ** end of parameter validation

		$this->_resourceId = $resourceId;
		
		$this->_numberOfRows = pg_affected_rows($this->_resourceId);

		// in PostGre, when inserting several rows with one INSERT query,
		// PostGre_insert_id() returns the id of the first row.
		// Thus, we need to add the number of inserted rows - 1 to get the actual
		// last id.
		$this->_lastAutoIncrementValue = pg_last_oid($this->_resourceId) + $this->getNumberOfRows() - 1;
	}
		

	/**
	 * Gets the last auto increment value that was generated by the INSERT query.
	 * Gets the last auto increment value that was generated by the INSERT query.
	 * @access public
	 * @return integer The last auto increment value that was generated by the INSERT query.
	 */ 
	function getLastAutoIncrementValue() {
		return $this->_lastAutoIncrementValue;
	}
	

	/**
	 * Returns the number of rows that the query processed.
	 * Returns the number of rows that the query processed. For a SELECT query,
	 * this would be the total number of rows selected. For a DELETE, UPDATE, or
	 * INSERT query, this would be the number of rows that were affected.
	 * @return integer Number of rows that were processed by the query.
	 * @access public
	 */ 
	function getNumberOfRows() {
		return $this->_numberOfRows;
	}


}

?>