<?php
/**
 * @package harmoni.dbc
 * 
 * @copyright Copyright &copy; 2005, Middlebury College
 * @license http://www.gnu.org/copyleft/gpl.html GNU General Public License (GPL)
 *
 * @version $Id: InsertQueryResult.interface.php,v 1.4 2007/09/05 21:38:59 adamfranco Exp $
 */
require_once("QueryResult.interface.php");

/**
 * The InsertQueryResult interface provides the functionality common to all INSERT query results.
 *
 * For example, you can get the primary key for the last insertion, get number of inserted rows, etc.
 *
 * @package harmoni.dbc
 * 
 * @copyright Copyright &copy; 2005, Middlebury College
 * @license http://www.gnu.org/copyleft/gpl.html GNU General Public License (GPL)
 *
 * @version $Id: InsertQueryResult.interface.php,v 1.4 2007/09/05 21:38:59 adamfranco Exp $
 */

interface InsertQueryResultInterface 
	extends QueryResultInterface 
{

	/**
	 * Gets the last auto increment value that was generated by the INSERT query.
	 * Gets the last auto increment value that was generated by the INSERT query.
	 * @access public
	 * @return integer The last auto increment value that was generated by the INSERT query.
	 */ 
	function getLastAutoIncrementValue();
}

?>