-- /**
-- @package harmoni.osid_v2.scheduling
-- 
-- 
-- @copyright Copyright &copy; 2006, Middlebury College
-- @license http://www.gnu.org/copyleft/gpl.html GNU General Public License (GPL)
-- 
-- @version $Id: MySQL_Scheduling.sql,v 1.1 2006/07/04 20:13:35 sporktim Exp $
-- */
-- --------------------------------------------------------